"""Configuration for standalone fisheye camera calibration."""

from pathlib import Path


CAPTURE_DIR = Path(__file__).resolve().parent
CALIBRATION_DATA_DIR = CAPTURE_DIR / "calibration_data"
CALIBRATION_IMAGE_DIR = CALIBRATION_DATA_DIR / "images"
CALIBRATION_DIAGNOSTIC_DIR = CALIBRATION_DATA_DIR / "diagnostics"
CALIBRATION_PROFILE_PATH = CALIBRATION_DATA_DIR / "fisheye_1280x720.json"

CAMERA_DEVICE = "/dev/video0"
CALIBRATION_WIDTH = 1280
CALIBRATION_HEIGHT = 720
CALIBRATION_FPS = 30
CALIBRATION_FOURCC = "MJPG"

# These are internal checkerboard corners, not the number of printed squares.
CHECKERBOARD_COLUMNS = 9
CHECKERBOARD_ROWS = 6
CHECKERBOARD_SQUARE_MM = 20.0

MINIMUM_CALIBRATION_IMAGES = 15
TARGET_CALIBRATION_IMAGES = 25
FISHEYE_BALANCE = 1.0
MAXIMUM_RMS_WARNING_PX = 2.0

PREVIEW_PROCESS_FPS = 8
PREVIEW_DISPLAY_MAX_WIDTH = 560
PREVIEW_DISPLAY_MAX_HEIGHT = 315
MINIMUM_SHARPNESS_SCORE = 60.0
